HuynhKimNganHaTien.SachOnline/Areas/Admin/Controllers/NhaXuatBanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HuynhKimNganHaTien.SachOnline.Models;

namespace HuynhKimNganHaTien.SachOnline.Areas.Admin.Controllers
{
    public class NhaXuatBanController : Controller
    {
        DataClasses1DataContext db = new DataClasses1DataContext();
        // GET: Admin/NhaXuatBan
        public ActionResult NXB()
        {
            return View(db.NHAXUATBANs);
        }
        public NHAXUATBAN LayNXB(int id)
        {
            return db.NHAXUATBANs.SingleOrDefault(nxb => nxb.MaNXB == id);

        }
        public ActionResult ChiTiet(int id)
        {
            return View(LayNXB(id));
        }
        [HttpGet]
        public ActionResult Sua(int id)
        {
            return View(LayNXB(id));
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Sua()
        {
            if (ModelState.IsValid)
            {
                var nxb = LayNXB(int.Parse(Request.Form["MaNXB"]));
                nxb.TenNXB = Request.Form["TenNXB"];
                nxb.DiaChi = Request.Form["DiaChi"];
                nxb.DienThoai = Request.Form["DienThoai"];
                db.SubmitChanges();
                return RedirectToAction("NXB");
            }
            else
            {
                return RedirectToAction("Sua");
            }
        }

        [HttpGet]
        public ActionResult Them()
        {
            return View();
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Them(NHAXUATBAN nxb)
        {
            if (ModelState.IsValid)
            {
                db.NHAXUATBANs.InsertOnSubmit(nxb);
                db.SubmitChanges();
                return RedirectToAction("NXB");
            }

            return View(nxb);
        }

        [HttpGet]
        public ActionResult Xoa(int id)
        {
            return View(LayNXB(id));
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Xoa(NHAXUATBAN nxb, int id)
        {
            using (var db = new DataClasses1DataContext())
            {
                var nxbToDelete = db.NHAXUATBANs.SingleOrDefault(NXB => NXB.MaNXB == id);
                if (nxbToDelete != null)
                {
                    db.NHAXUATBANs.DeleteOnSubmit(nxbToDelete);
                    db.SubmitChanges();
                }
            }

            return RedirectToAction("NXB");
        }

    }
}

HuynhKimNganHaTien.SachOnline/Areas/Admin/Views/NhaXuatBan/ChiTiet.cshtml
@model HuynhKimNganHaTien.SachOnline.Models.NHAXUATBAN

@{
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ChiTiet</title>
</head>
<body>
    <div>
        <h4>NHAXUATBAN</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.TenNXB)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.TenNXB)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.DiaChi)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.DiaChi)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.DienThoai)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.DienThoai)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Sua", "Sua", new { id = Model.MaNXB }) |
        @Html.ActionLink("Back to List", "NXB")
    </p>
</body>
</html>

HuynhKimNganHaTien.SachOnline/Areas/Admin/Views/NhaXuatBan/NXB.cshtml
@model IEnumerable<HuynhKimNganHaTien.SachOnline.Models.NHAXUATBAN>

@{
    ViewBag.Title = "ChiTietNXB";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>IndexAdmin</h2>

<p>
    @Html.ActionLink("Create New", "Them")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TenNXB)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DiaChi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DienThoai)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TenNXB)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DiaChi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DienThoai)
            </td>
            <td>
                @Html.ActionLink("Edit", "Sua", new { id = item.MaNXB }) |
                @Html.ActionLink("Details", "ChiTiet", new { id = item.MaNXB }) |
                @Html.ActionLink("Delete", "Xoa", new { id = item.MaNXB })
            </td>
        </tr>
    }

</table>

HuynhKimNganHaTien.SachOnline/Areas/Admin/Views/NhaXuatBan/Sua.cshtml
@model HuynhKimNganHaTien.SachOnline.Models.NHAXUATBAN

@{
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @using (Html.BeginForm("Sua", "NhaXuatBan"))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            <h4>SỬA NHÀ XUẤT BẢN</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.MaNXB)
            <div class="form-group">
                @Html.LabelFor(model => model.MaNXB, htmlAttributes: new { @class = "controllabel col-md-2" })
                <div class="col-md-10">
                    <div class="form-control">@Model.MaNXB</div>
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.TenNXB, htmlAttributes: new { @class = "controllabel col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TenNXB, new
                    {
                        htmlAttributes = new
                        {
                            @class =
                   "form-control"
                        }
                    })
                    @Html.ValidationMessageFor(model => model.TenNXB, "", new { @class = "textdanger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.DiaChi, htmlAttributes: new
                {
                    @class = "control-labelcol - md - 2"
                })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DiaChi, new
                    {
                        htmlAttributes = new
                        {
                            @class = "form-control"
                        }
                    })
                    @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "textdanger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.DienThoai, htmlAttributes: new { @class = "controllabel col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DienThoai, new
                    {
                        htmlAttributes = new
                        {
                            @class = "form-control"
                        }
                    })
                    @Html.ValidationMessageFor(model => model.DienThoai, "", new { @class = "textdanger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "ChiTiet")
    </div>
</body>
</html>

HuynhKimNganHaTien.SachOnline/Areas/Admin/Views/NhaXuatBan/Them.cshtml
@model HuynhKimNganHaTien.SachOnline.Models.NHAXUATBAN

@{
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Them</title>
</head>
<body>
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>NHAXUATBAN</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.TenNXB, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TenNXB, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TenNXB, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.DiaChi, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.DienThoai, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DienThoai, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DienThoai, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "NXB")
    </div>
</body>
</html>

HuynhKimNganHaTien.SachOnline/Areas/Admin/Views/NhaXuatBan/Xoa.cshtml
@model HuynhKimNganHaTien.SachOnline.Models.NHAXUATBAN

@{
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Xoa</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>NHAXUATBAN</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.TenNXB)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.TenNXB)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.DiaChi)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.DiaChi)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.DienThoai)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.DienThoai)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>