HuynhKimNganHaTien.SachOnline/Controllers/SachOnlineController.cs
using HuynhKimNganHaTien.SachOnline.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using PagedList;
using PagedList.Mvc;
using System.Linq.Dynamic;
using System.Linq.Expressions;

namespace HuynhKimNganHaTien.SachOnline.Controllers
{
    public class SachOnlineController : Controller
    {
        DataClasses1DataContext db = new DataClasses1DataContext();

        // GET: SachOnline
        public ActionResult Index(int page = 1)
        {
            var cd = from c in db.SACHes select c;

            int pageSize = 6;
            var sachPagedList = cd.ToPagedList(page, pageSize);

            return View(sachPagedList);
        }
        public ActionResult ChuDePartial()
        {
            var cd = from c in db.CHUDEs select c;
            return PartialView(cd);
        }
        public ActionResult NhaXuatBanPartial()
        {
            var cd = from c in db.NHAXUATBANs select c;

            return PartialView(cd);
        }
        [ChildActionOnly]
        public ActionResult NAVPartial()
        {
            List<MENU> lst = new List<MENU>();
            lst = db.MENUs.Where(m => m.ParentId == null).OrderBy(m => m.OrderNumber).ToList(); int[] a = new int[lst.Count()];
            for (int i = 0; i < lst.Count; i++)
            {
                var l = db.MENUs.Where(m => m.ParentId
                ==
                lst[i].Id);
                a[i] = l.Count();
            }
            ViewBag.lst = a;
            return PartialView(lst);
        }
        public ActionResult SliderPartial()
        {
            return PartialView();
        }
        public ActionResult SachBanNhieuPartial()
        {
            var sachBanNhieu = db.SACHes
                                .OrderByDescending(s => s.SoLuongBan)
                                .Take(6)
                                .ToList();

            return PartialView(sachBanNhieu);
        }
        public ActionResult FooterPartial()
        {
            return PartialView();
        }
        public ActionResult Search(string keyword = null, int maCD = 0)
        {
            ViewBag.cd = db.CHUDEs.ToList();
            var searchResults = db.SACHes.AsQueryable();

            if (maCD != 0)
            {
                searchResults = searchResults.Where(book => book.CHUDE.MaCD == maCD);
            }

            if (!string.IsNullOrEmpty(keyword))
            {
                searchResults = searchResults.Where(book => book.TenSach.Contains(keyword));
            }

            return View(searchResults.ToList());
        }

        public ActionResult ChiTietSach(int id)
        {
            var sach = from s in db.SACHes where s.MaSach == id select s;

            return View(sach.Single());
        }

        public ActionResult Group()
        {
            var kq = from s in db.SACHes group s by s.MaCD;
            //var kq = db.SACHes.GroupBy(s => s.MaCD);
            return View(kq);
        }

        public ActionResult ThongKe()
        {
            var kq = from s in db.SACHes
                     join cd in db.CHUDEs on s.MaCD equals cd.MaCD
                     group s by new { cd.MaCD, cd.TenChuDe } into g
                     select new ReportInfo
                     {
                         Id = g.Key.MaCD.ToString(), // Mã CD
                         Name = g.Key.TenChuDe,      // Tên CD
                         Count = g.Count(),
                         Sum = g.Sum(n => n.SoLuongBan),
                         Max = g.Max(n => n.SoLuongBan),
                         Min = g.Min(n => n.SoLuongBan),
                         Avg = Convert.ToDecimal(g.Average(n => n.SoLuongBan))
                     };
            return View(kq);
        }

        public ActionResult Searchphantrang(int? page, string strSearch = null)
        {
            ViewBag.Search = strSearch;
            if (!string.IsNullOrEmpty(strSearch))
            {
                int iSize = 3;
                int iPageNumber = (page ?? 1);
                var kq = from s in db.SACHes where s.TenSach.Contains(strSearch) || s.MoTa.Contains(strSearch) select s;
                return View(kq.ToPagedList(iPageNumber, iSize));
            }
            return View();
        }



        public ActionResult Searchphantrangtuychon(int? page, int? size, string strSearch = null)
        {
            List<SelectListItem> items = new List<SelectListItem>();
            items.Add(new SelectListItem { Text = "3", Value = "3" });
            items.Add(new SelectListItem { Text = "5", Value = "5" });
            items.Add(new SelectListItem { Text = "10", Value = "10" });
            items.Add(new SelectListItem { Text = "20", Value = "20" });
            items.Add(new SelectListItem { Text = "25", Value = "25" });
            items.Add(new SelectListItem { Text = "50", Value = "50" });

            foreach (var item in items)
            {
                if (item.Value == size.ToString()) item.Selected = true;
            }

            ViewBag.size = items;
            ViewBag.currentSize = size;
            ViewBag.Search = strSearch;

            int iSize = size ?? 3;
            int iPageNumber = page ?? 1;

            var kq = from s in db.SACHes select s;

            if (!string.IsNullOrEmpty(strSearch))
            {
                kq = kq.Where(s => s.TenSach.Contains(strSearch) || s.MoTa.Contains(strSearch));
            }

            return View(kq.ToPagedList(iPageNumber, iSize));
        }



        public ActionResult Searchphantrangsapxep(int? page, string sortProperty, string sortOrder = "", string strSearch = null)
        {
            ViewBag.Search = strSearch;
            if (!string.IsNullOrEmpty(strSearch))
            {
                int iSize = 3;
                int iPageNumber = page ?? 1;
                if (sortOrder == "") ViewBag.SortOrder = "desc";
                if (sortOrder == "desc") ViewBag.SortOrder = "";
                if (sortOrder == "") ViewBag.SortOrder = "asc";
                if (string.IsNullOrEmpty(sortProperty))
                    sortProperty = "TenSach";
                ViewBag.SortProperty = sortProperty;
                var kq = from s in db.SACHes where s.TenSach.Contains(strSearch) || s.MoTa.Contains(strSearch) select s;
                if (sortOrder == "desc")
                {
                    kq = kq.OrderBy(sortProperty + "desc");
                }
                else
                {
                    kq = kq.OrderBy(sortProperty);
                }
                return View(kq.ToPagedList(iPageNumber, iSize));

            }
            return View();
        }
        public ActionResult LoginLogout()
        {
            return PartialView("LoginLogoutPartial");
        }

        public ActionResult SachCD(int maCD, int pageNumber = 1, int pageSize = 1)
        {
            var sachLienQuan = (from s in db.SACHes where s.MaCD == maCD select s).ToPagedList(pageNumber, pageSize);

            return View("SachCD", sachLienQuan);
        }


        public ActionResult SachNXB(int maNXB, int pageNumber = 1, int pageSize = 1)
        {
            var sachLienQuan = (from s in db.SACHes where s.MaNXB == maNXB select s).ToPagedList(pageNumber, pageSize);

            return View("SachNXB", sachLienQuan);
        }
        [ChildActionOnly]
        public ActionResult LoadChildMenu(int parentId)
        {
            List<MENU> lst = new List<MENU>();
            lst = db.MENUs.Where(m => m.ParentId == parentId).OrderBy(m => m.OrderNumber).ToList(); ViewBag.Count = lst.Count();
            int[] a = new int[lst.Count()];
            for (int i = 0; i < lst.Count; i++)
            {
                var l = db.MENUs.Where(m => m.ParentId == lst[i].Id); a[i] = l.Count();
            }
            ViewBag.lst = a;
            return PartialView("LoadChildMenu", lst);

        }
        public ActionResult TrangTin(string metatitle)
        {
            var tt = (from t in db.TRANGTINs where t.MetaTitle == metatitle select t).Single();
            return View(tt); 
        }

    }
}

HuynhKimNganHaTien.SachOnline/Views/Shared/ChuDePartial.cshtml
@{
    ViewBag.Title = "ChudePartial";
}

@model IEnumerable<HuynhKimNganHaTien.SachOnline.Models.CHUDE>
<ul class="list-group">
    <li class="list-group-item active" style="font-weight:bold; text-align:center">SÁCH THEO CHỦ ĐỀ</li>
    @foreach (var item in Model)
    {
        @Html.ActionLink(item.TenChuDe, "SachCD", "SachOnline", new { maCD = item.MaCD }, new { @class = "list-group-item" })
    }
</ul>

HuynhKimNganHaTien.SachOnline/Views/Shared/FooterPartial.cshtml
<footer class="container well">
    <div class="row">
        <div class="col-lg-9 col-md-9 col-sm-9 col-xs-6" style="text-align:center;">
            <p>©2021 - Nhà sách ABC. Allright Reserved</p>
            <p>
                Website được phát triển để sử dụng làm bài tập thực hành môn Lập trình
                Web
            </p>
            <p>Email: abc@gmail.com</p>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-9 col-xs-6 foot">
            <h5 style=" color: red;">Số lượt truy cập: @ApplicationInstance.Application["HitCounter"]</h5>
            <h5 style=" color: red;">Số người online: @ApplicationInstance.Application["Online"]</h5>
        </div>
    </div>

</footer>

HuynhKimNganHaTien.SachOnline/Views/Shared/GioHangPartial.cshtml
    <a href="@Url.Action("GioHang", "GioHang")">
        <span class="glyphicon glyphicon-shopping-cart"></span>
        Giỏ hàng (@ViewBag.TongSoLuong)
    </a>

HuynhKimNganHaTien.SachOnline/Views/Shared/LayoutUser.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <style type="text/css">
        .imgbook {
            transition: all 1s ease-in;
            width: 400px;
        }

            .imgbook:hover {
                transform: scale(0.9);
                cursor: pointer;
            }

        .imgsachbannhieu {
            width: 100px;
        }
    </style>
</head>
<body>
    <div>
        <header>
            @Html.Action("NAVPartial", "SachOnline")
        </header>
        <article>
            @RenderSection("SliderPartial", required: false)
        </article>
        <section>
            <div class="container">
                <div class="row">
                    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                        @Html.Action("ChuDePartial", "SachOnline")
                        <br>
                        @Html.Action("NhaXuatBanPartial", "SachOnline")

                    </div>
                    @RenderBody()
                </div>
            </div>

            <hr>

    </div>
    </section>
    <aside>
        @RenderSection("SachBanNhieuPartial", required: false)
    </aside>
    </div>
    @Html.Action("FooterPartial", "SachOnline")
    </div>
</body>
</html>

HuynhKimNganHaTien.SachOnline/Views/Shared/LoadChildMenu.cshtml
@model IEnumerable<HuynhKimNganHaTien.SachOnline.Models.MENU>
@{
    int i = 0;
    @:<ul class="dropdown-menu">
        foreach (var item in Model)
        {
            if (ViewBag.lst[i] != 0)
            {
                <li class="dropdown-submenu">
                    <a href="#" class="test list-group-item">
                        @item.MenuName <span class="caret"></span>
                    </a>
                    @Html.Action("LoadChildMenu", "SachOnline", new { parentId = item.Id })
                </li>
            }
            else
            {
                <li>
                    <a href="~/@item.MenuLink" class="list-group-item">@item.MenuName</a>
                </li>
            }
            i++;
        }
    @:</ul>
}
<style>
    .dropdown-submenu {
        position: relative;
    }

        .dropdown-submenu .dropdown-menu {
            top: 0;
            left: 100%;
            margin-top: -1px;
        }
</style>
<script>
    $(document).ready(function () {
        $('.dropdown-submenu a.test').on("click", function (e) {
            $(this).next('ul').toggle();

            e.stopPropagation(); /*Phương thức stopPropagation() của đối tượng event
             * được sử dụng để ngăn không cho sự kiện lan toả lên các phần tử cha
             * của phần tử diễn ra sự kiện.*/
            e.preventDefault(); /*Phương thức preventDefault() của đối tượng event
             * được sử dụng để ngăn chặn xử lý mặc định của trình duyệt khi xảy ra sự kiện.*/
        });
    });
</script>

HuynhKimNganHaTien.SachOnline/Views/Shared/LoginLogoutPartial.cshtml
@using HuynhKimNganHaTien.SachOnline.Models
@{
    KHACHHANG kh = (KHACHHANG)Session["TaiKhoan"];
}
@if (Session["TaiKhoan"] == null) //Giao diện Login
{
    <li>
        <a href="~/User/DangKy">
            <span class="glyphicon glyphicon-user"></span>
            Đăng ký
        </a>
    </li>

    <li>
        <a href="~/User/DangNhap?id=1">
            <span class="glyphicon glyphicon-log-
in"></span> Đăng nhập
        </a>
    </li>

}
else
 //Giao diện Logout
{
<li>
    <a href="#">
        <span class="glyphicon glyphicon-user"></span> Xin chào:@kh.HoTen
    </a>
</li>

<li>
    <a href="@Url.Action("DangXuat","User")">
        <span class="glyphicon glyphicon-log-
out"></span> Đăng xuất
    </a>
</li>

}

HuynhKimNganHaTien.SachOnline/Views/Shared/NAVPartial.cshtml
@{
    ViewBag.Title = "NavPartial";

}
@model IEnumerable<HuynhKimNganHaTien.SachOnline.Models.MENU>

<nav class="navbar navbar-inverse">
    <!--navbar-fixed-top-->
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data- target="#navbar1" aria-expanded="false">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">SachOnline</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling (Chứa nội dung của navbar) -->
        <div class="collapse navbar-collapse" id="navbar1">
            <ul class="nav navbar-nav">
                @{
                    int i = 0;
                    foreach (var item in Model)
                    {
                        if (ViewBag.lst[i] != 0)
                        {
                            <li class="dropdown">
                                <a href="@item.MenuLink" class="dropdown-toggle"
                                   data-toggle="dropdown" role="button" aria-expanded="false" aria-
                                   haspopup="true">
                                    @item.MenuName<span class="caret"></span>
                                </a>
                                @Html.Action("LoadChildMenu", "SachOnline", new
                                {
                                    parentId =
                                item.Id
                                })
                            </li>
                        }
                        else
                        {
                            <li><a href="~/@item.MenuLink">@item.MenuName</a> </li>
                        }
                        i++;
                    }
                }
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    @if (Session["TaiKhoan"] != null)
                    {
                        // Hiển thị menu cho người dùng đã đăng nhập
                        @Html.Action("LoginLogout", "SachOnline")
                    }
                    else
                    {
                        // Hiển thị menu cho người dùng chưa đăng nhập
                        @Html.Action("LoginLogout", "SachOnline")
                    }
                <li>
                    @Html.Action("GioHangPartial", "GioHang")
                </li>
            </ul>

            <form class="navbar-form navbar-right" role="search" action="@Url.Action("Search", "SachOnline")" method="GET">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Tìm kiếm" name="keyword">
                </div>
                <button type="submit" class="btn btn-default">Tìm</button>
            </form>

        </div>
        <!-- /.navbar-collapse -->

    </div>
    <!-- /.container-->
</nav>

HuynhKimNganHaTien.SachOnline/Views/Shared/NhaXuatBanPartial.cshtml
@{
    ViewBag.Title = "NXBPartial";
}

@model IEnumerable<HuynhKimNganHaTien.SachOnline.Models.NHAXUATBAN>
<ul class="list-group">
    <li class="list-group-item active" style="font-weight:bold; text-align:center">SÁCH THEO NHÀ XUẤT BẢN</li>
    @foreach (var item in Model)
    {
        @Html.ActionLink(item.TenNXB, "SachNXB", "SachOnline", new { manxb = item.MaNXB }, new { @class = "list-group-item" })

    }
</ul>

HuynhKimNganHaTien.SachOnline/Views/Shared/SachBanNhieuPartial.cshtml
@model List<HuynhKimNganHaTien.SachOnline.Models.SACH>
<div class="container">
    <h2 class="text-center">SÁCH BÁN NHIỀU</h2>
    <div class="row">
        @foreach (var sach in Model)
        {
            <div class="col-lg-6 col-md-6">
                <div class="media-object-default">
                    <div class="media">
                        <div class="media-left">
                            <a href="@Url.Action("ChiTietSach", "SachOnline", new { id = sach.MaSach })">
                                <img class="media-object imgsachbannhieu"
                                     src="~/Images/@sach.AnhBia" alt="@sach.TenSach">
                            </a>
                        </div>
                        <div class="media-body">
                            <b class="media-heading" font-size: 15px>@sach.TenSach</b>
                            <br>
                            Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm.
                            @*@sach.MoTa</p>*@
                            <!-- Thêm các thông tin khác của sách -->
                        </div>
                    </div>
                </div>
            </div>

        }
    </div>
    <!-- row-->
    <hr>
</div>
<!-- /.container-->

<!--<div class="container">

    <h2 class="text-center">SÁCH BÁN NHIỀU</h2>
    <div class="row">
        <div class="col-lg-6 col-md-6">
            <div class="media-object-default">
                <div class="media">
                    <div class="media-left">
                        <a href="#">
                            <img class="media-object imgsachbannhieu"
                                 src="~/Images/TH004.jpg" alt="placeholder image">
                        </a>
                    </div>
                    <div class="media-body">
                        <h4 class="media-heading">Tên sản phẩm </h4>
                        Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm.
                    </div>
                </div>
                <div class="media">
                    <div class="media-left">
                        <a href="#">
                            <img class="media-object imgsachbannhieu"
                                 src="~/Images/TH005.jpg" alt="placeholder image">
                        </a>
                    </div>
                    <div class="media-body">
                        <h4 class="media-heading">Tên sản phẩm </h4>
                        Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm.
                    </div>
                </div>
                <div class="media">
                    <div class="media-left">
                        <a href="#">
                            <img class="media-object imgsachbannhieu"
                                 src="~/Images/TH006.jpg" alt="placeholder image">
                        </a>
                    </div>
                    <div class="media-body">
                        <h4 class="media-heading">Tên sản phẩm </h4>
                        Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm.
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-6 col-md-6">
            <div class="media-object-default">
                <div class="media">
                    <div class="media-left">
                        <a href="#">
                            <img class="media-object imgsachbannhieu"
                                 src="~/Images/TH007.jpg" alt="placeholder image">
                        </a>
                    </div>
                    <div class="media-body">
                        <h4 class="media-heading">Tên sản phẩm </h4>
                        Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm.
                    </div>
                </div>
                <div class="media">
                    <div class="media-left">
                        <a href="#">
                            <img class="media-object imgsachbannhieu"
                                 src="~/Images/TH008.jpg" alt="placeholder image">
                        </a>
                    </div>
                    <div class="media-body">
                        <h4 class="media-heading">Tên sản phẩm </h4>
                        Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm.
                    </div>
                </div>
                <div class="media">
                    <div class="media-left">
                        <a href="#">
                            <img class="media-object imgsachbannhieu"
                                 src="~/Images/THCB.jpg" alt="placeholder image">
                        </a>
                    </div>
                    <div class="media-body">
                        <h4 class="media-heading">Tên sản phẩm </h4>
                        Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm. Mô tả chi tiết sản phẩm.
                    </div>
                </div>
            </div>
        </div>

    </div>
    <hr>
</div>
-->

HuynhKimNganHaTien.SachOnline/Views/Shared/SliderPartial.cshtml
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

            <div id="carousel1" class="carousel slide">
                <ol class="carousel-indicators">
                    <li data-target="#carousel1" data-slide-to="0" class="active"> </li>
                    <li data-target="#carousel1" data-slide-to="1" class=""> </li>
                    <li data-target="#carousel1" data-slide-to="2" class=""> </li>
                    <li data-target="#carousel1" data-slide-to="3" class=""> </li>
                    <li data-target="#carousel1" data-slide-to="4" class=""> </li>
                    <li data-target="#carousel1" data-slide-to="5" class=""> </li>
                </ol>
                <div class="carousel-inner">
                    <div class="item active">
                        <img class="img-responsive" src="~/Images/Slider/01.jpg" alt="thumb">
                        <div class="carousel-caption"> Quảng cáo 1 </div>
                    </div>
                    <div class="item">
                        <img class="img-responsive" src="/Images/Slider/02.jpg" alt="thumb">
                        <div class="carousel-caption"> Quảng cáo 2 </div>
                    </div>
                    <div class="item">
                        <img class="img-responsive" src="/Images/Slider/03.jpg" alt="thumb">
                        <div class="carousel-caption"> Quảng cáo 3 </div>
                    </div>
                    <div class="item">
                        <img class="img-responsive" src="/Images/Slider/04.jpg" alt="thumb">
                        <div class="carousel-caption"> Quảng cáo 4 </div>
                    </div>
                    <div class="item">
                        <img class="img-responsive" src="/Images/Slider/05.jpg" alt="thumb">
                        <div class="carousel-caption"> Quảng cáo 5 </div>
                    </div>
                    <div class="item">
                        <img class="img-responsive" src="/Images/Slider/06.jpg" alt="thumb">
                        <div class="carousel-caption"> Quảng cáo 6 </div>
                    </div>
                </div>
                <a class="left carousel-control" href="#carousel1" data-slide="prev"><span class="icon- prev"></span></a> <a class="right carousel-control" href="#carousel1" data-slide="next"><span class="icon-next"></span></a>
            </div>
        </div>